[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"

[[redirects]]
  from = "/api/ai-chat"
  to = "/.netlify/functions/ai-chat"
  status = 200
